name: networking
path: git::https://github.com/awslabs/idf-modules.git//modules/network/basic-cdk
parameters:
  - name: internet-accessible
    value: true
---
name: dcv
path: git::https://github.com/awslabs/idf-modules.git//modules/storage/ecr?ref=release/1.3.0&depth=1
parameter:
  - name: image-tag-mutability
    value: "MUTABLE"
# ---
# name: datalake-buckets
# path: git::https://github.com/awslabs/autonomous-driving-data-framework.git//modules/optionals/datalake-buckets
# parameters:
#   - name: encryption-type
#     value: SSE