name: test-deploy
toolchainRegion: eu-west-2
groups:
  - name: replication
    path: manifests/demo-isolated/replicator-modules.yaml
  - name: core
    path: manifests/demo-isolated/core-modules.yaml
targetAccountMappings:
  - alias: primary
    accountId: 1234567890
    default: true
    # parametersGlobal:
    regionMappings:
      - region: eu-west-2
        default: true
        parametersRegional:
          dockerCredentialsSecret: aws-addf-docker-credentials
          # replace the below networking details with customer specific values
          vpcId: vpc-XXXXXXXX
          publicSubnetIds:
            - subnet-XXXXXXXX
            - subnet-XXXXXXXX
          privateSubnetIds:
            - subnet-XXXXXXXX
            - subnet-XXXXXXXX
          isolatedSubnetIds:
            - subnet-XXXXXXXX
            - subnet-XXXXXXXX
          securityGroupIds:
            - sg-XXXXXXXX
        # these networking values will be used for seedfarmer's codebuild environment
        network: 
          vpcId:
            valueFrom:
              parameterValue: vpcId
            # Alternatively you can grab the networking values from SSM parameter store
            # valueFrom:
            #   parameterStore: /addf/vpc-id
          privateSubnetIds:
            valueFrom:
              parameterValue: privateSubnetIds
            # Alternatively you can grab the networking values from SSM parameter store
            # valueFrom:
            #   parameterStore: /addf/private-ids
          securityGroupIds:
            valueFrom:
              parameterValue: securityGroupIds
            # Alternatively you can grab the codebuild security group from SSM parameter store
            # valueFrom:
            #   parameterStore: /addf/sg-ids