name: eks-os
path: modules/integration/eks-to-opensearch/
parameters:
  - name: eks-cluster-admin-role-arn
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterAdminRoleArn
  - name: eks-cluster-name
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterName
  - name: eks-cluster-sg-id
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksClusterSecurityGroupId
  - name: eks-oidc-arn
    valueFrom:
      moduleMetadata:
        group: core
        name: eks
        key: EksOidcArn
  - name: opensearch-sg-id
    valueFrom:
      moduleMetadata:
        group: core
        name: opensearch
        key: OpenSearchSecurityGroupId
  - name: opensearch-domain-endpoint
    valueFrom:
      moduleMetadata:
        group: core
        name: opensearch
        key: OpenSearchDomainEndpoint
---
name: rosbag-ddb-to-os
path: modules/integration/ddb-to-opensearch/
parameters:
  - name: opensearch-domain-name
    valueFrom:
      moduleMetadata:
        group: core
        name: opensearch
        key: OpenSearchDomainName
  - name: opensearch-domain-endpoint
    valueFrom:
      moduleMetadata:
        group: core
        name: opensearch
        key: OpenSearchDomainEndpoint
  - name: opensearch-sg-id
    valueFrom:
      moduleMetadata:
        group: core
        name: opensearch
        key: OpenSearchSecurityGroupId
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: VpcId
  - name: private-subnet-ids
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: PrivateSubnetIds
  - name: rosbag_stream_arn
    valueFrom:
      moduleMetadata:
        group: core
        name: metadata-storage
        key: RosbagSceneMetadataStreamArn
---
name: emrlogs-to-os
path: modules/integration/emr-to-opensearch/
parameters:
  - name: opensearch-domain-name
    valueFrom:
      moduleMetadata:
        group: core
        name: opensearch
        key: OpenSearchDomainName
  - name: opensearch-domain-endpoint
    valueFrom:
      moduleMetadata:
        group: core
        name: opensearch
        key: OpenSearchDomainEndpoint
  - name: opensearch-sg-id
    valueFrom:
      moduleMetadata:
        group: core
        name: opensearch
        key: OpenSearchSecurityGroupId
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: VpcId
  - name: private-subnet-ids
    valueFrom:
      moduleMetadata:
        group: optionals
        name: networking
        key: PrivateSubnetIds
  - name: logs-bucket-name
    valueFrom:
      moduleMetadata:
        group: optionals
        name: datalake-buckets
        key: LogsBucketName
  - name: emr-logs-prefix
    value: "elasticmapreduce"
