name: networking
path: git::https://github.com/awslabs/idf-modules.git//modules/network/basic-cdk?ref=release/1.11.0&depth=1
parameters:
  - name: internet-accessible
    value: true
---
name: datalake-buckets
path: modules/optionals/datalake-buckets
parameters:
  - name: encryption-type
    value: SSE
